name: IOS

on:
  push:
    branches:
        - master


jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@master

      - name: Print working directory
        run: pwd

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          BUILD_CERTIFICATE_BASE64_DEV: ${{ secrets.BUILD_CER_DEVELOPMENT }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          BUILD_PROVISION_PROFILE_BASE64_DEV: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_DEV }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          CERTIFICATE_PATH_DEV=$RUNNER_TEMP/build_certificate_dev.p12
          PP_PATH=$RUNNER_TEMP/b3c0fa0f-2f54-46d4-8460-321cea389d0d.mobileprovision
          PP_PATH_DEV=$RUNNER_TEMP/4c13e7aa-e382-4565-afa8-0c30d97b6b89.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_CERTIFICATE_BASE64_DEV" | base64 --decode --output $CERTIFICATE_PATH_DEV
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64_DEV" | base64 --decode --output $PP_PATH_DEV

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH_DEV -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH_DEV ~/Library/MobileDevice/Provisioning\ Profiles

          echo "complete"

          ls ~/Library/MobileDevice/Provisioning\ Profiles

      # - name: prepare
      #   run: |
      #     swift package init
      #     swift package generate-xcodeproj

      - name: archive
        run: xcodebuild archive -project ./GithubAction/GithubAction.xcodeproj -scheme GithubAction -configuration release -archivePath ./output/GithubAction.xcarchive

      - name: export
        run: xcodebuild -exportArchive -archivePath ./output/GithubAction.xcarchive -exportPath ./output -exportOptionsPlist ./ExportOptions.plist
        # run: swift build -v
