name: IOS

on:
  push:
    branches:
        - master


jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@master
      - name: print working directory
        run: pwd
      # - name: prepare
      #   run: |
      #     swift package init
      #     swift package generate-xcodeproj
      - name: archive
        run: xcodebuild archive -project ./GithubAction/GithubAction.xcodeproj -scheme GithubAction -configuration release -archivePath ./output/GithubAction.xcarchive
      - name: export
        run: xcodebuild -exportArchive -archivePath ./output/GithubAction.xcarchive -exportPath ./output -exportOptionsPlist ./output/ExportOptions.plist
        # run: swift build -v
